[package]
name = "demo01helloworld"
version = "0.1.0"
authors = ["sepiggy <jms1209@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
